{% set name = "neptune-pytorch-lightning" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7fb0e5f8d927a64f11e7ed2fdc5f64d180e064e9ffa15d8c271d4b66c58b1039

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - neptune-client >=0.9.8
    - pytorch-lightning

test:
  imports:
    - neptune_pytorch_lightning.impl
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with PyTorch Lightning
  doc_url: https://docs.neptune.ai/integrations-and-supported-tools/model-training/pytorch-lightning
  dev_url: https://github.com/neptune-ai/neptune-pytorch-lightning

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - PiotrJander
    - shnela
    - pkasprzyk
